version: "3.9"
services:
  db:
    image: postgres:14
    container_name: sample_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      # コンテナ起動時に initdb/ 以下の SQL を自動実行
      - ./initdb:/docker-entrypoint-initdb.d
  notebook:
    image: jupyter/datascience-notebook
    # ポートの設定("ホスト：コンテナ")
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./src:/home/jovyan/src
    # 最後にjupyterLabに接続するためのコマンドを実行する。
    command: start-notebook.sh --NotebookApp.token=''
